"""End-to-end scenario test: repeatedly combine 4 active environments, swap
a random slot for the freshly generated one, and repeat - so later steps
combine base environments with already-generated (and increasingly
higher-tier) ones, same as real play. Sanity-checks that every result is
internally consistent (bounded traits/weights, tier can only grow, the name
actually reflects what went into it), and writes a readable markdown report
to tests/output/generation_scenario.md on every run so the naming/tier
progression can be reviewed without re-running anything.
"""

import random
from pathlib import Path

import pytest

from app.game_engine.environment_generator import World
from app.game_engine.naming import COSMIC_TEMPLATES, words_for_element

BASE_KEYS = ["air", "earth", "water", "fire"]
STEPS = 10
OUTPUT_PATH = Path(__file__).parent / "output" / "generation_scenario.md"


def _random_ratios(n=4):
    raw = [random.random() + 0.01 for _ in range(n)]
    total = sum(raw)
    return [r / total for r in raw]


def _name_reflects_composition(name: str, weights: dict[str, float], tier: float) -> bool:
    full_weights = {el: weights.get(el, 0.0) for el in ("fire", "water", "earth", "air")}
    ordered = sorted(full_weights.items(), key=lambda kv: kv[1], reverse=True)
    dominant = ordered[0][0]
    if tier >= 11.0:
        return any(phrase in name for phrase in COSMIC_TEMPLATES[dominant])
    second = ordered[1][0]
    candidates = words_for_element(dominant) | words_for_element(second)
    return any(word in name for word in candidates)


@pytest.fixture(scope="session", autouse=True)
def _reset_output_file():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        "# Generation scenario traces\n\n"
        "Auto-generated by `pytest tests/test_generation_scenario.py` - "
        "10 steps per seed, starting from the 4 base environments and "
        "swapping a random slot for each freshly generated child.\n",
        encoding="utf-8",
    )


@pytest.mark.parametrize("seed", range(5))
def test_ten_step_generation_chain_is_internally_consistent(seed):
    random.seed(seed)
    world = World()
    active = list(BASE_KEYS)
    rows = []
    last_tier = 0.0

    for step in range(1, STEPS + 1):
        ratios = _random_ratios()
        child = world.generate(active, ratios)

        assert child.name
        assert child.tier >= 1.0 - 1e-9
        assert abs(sum(child.weights.values()) - 1.0) < 1e-6
        assert all(0.0 <= v <= 1.0 for v in child.weights.values())
        assert all(0.0 <= v <= 1.0 for v in child.traits.values())
        assert _name_reflects_composition(child.name, child.weights, child.tier), (
            f"{child.name!r} doesn't reflect its composition {child.weights}"
        )

        replace_idx = random.randrange(4)
        parents_desc = ", ".join(
            f"{name} {ratio:.2f}" for name, ratio in zip(active, ratios, strict=False)
        )
        replaced_desc = f"slot {replace_idx} ({active[replace_idx]})"
        rows.append(
            f"| {step} | {parents_desc} | **{child.name}** | {child.tier:.2f} | {replaced_desc} |"
        )
        active[replace_idx] = child.name
        last_tier = child.tier

    report = [
        f"\n## Seed {seed}\n",
        "| Step | Parents & ratios | New environment | Tier | Slot replaced |",
        "|---|---|---|---|---|",
        *rows,
        f"\nFinal active set: `{active}` - last tier: {last_tier:.2f}\n",
    ]
    with OUTPUT_PATH.open("a", encoding="utf-8") as f:
        f.write("\n".join(report) + "\n")
